version: '3.8'

services:
  api:
    build:
      context: ./Api.EndPoint
      dockerfile: Dockerfile.backend
      args:
        - NODE_ENV=production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    dns:
      - 178.22.122.100
      - 185.51.200.2
    restart: unless-stopped

  frontend:
    build:
      context: ./Site.EndPoint
      dockerfile: Dockerfile.frontend
      args:
        - NODE_ENV=production
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network
    dns:
      - 178.22.122.100
      - 185.51.200.2
    restart: unless-stopped

  admin:
    build:
      context: ./admin-endpoint
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3001:3000"
    depends_on:
      - api
    networks:
      - app-network
    dns:
      - 178.22.122.100
      - 185.51.200.2
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
