version: '3.8'

services:
  api:
    build:
      context: ./Api.EndPoint
      dockerfile: Dockerfile.backend
      target: prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/meraj-school
      - CORS_ORIGIN=http://mohammadrezasardashti.ir
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./Site.EndPoint
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
